const { token } = require("../app");

const spotifyGenres = [
    "acoustic",
    "alternative",
    "bluegrass",
    "blues",
    "folk",
    "grunge",
    "guitar",
    "happy",
    "hard-rock",
    "hardcore",
    "hardstyle",
    "heavy-metal",
    "hip-hop",
    "jazz",
    "malay",
    "mandopop",
    "metal",
    "metal-misc",
    "metalcore",
    "minimal-techno",
    "movies",
    "mpb",
    "party",
    "piano",
    "pop",
    "pop-film",
    "post-dubstep",
    "power-pop",
    "progressive-house",
    "punk",
    "punk-rock",
    "r-n-b",
    "rainy-day",
    "road-trip",
    "rock",
    "rock-n-roll",
    "romance",
    "sad",
    "sleep",
    "songwriter",
    "soul",
    "soundtracks",
    "study",
    "summer",
    "work-out",
];

module.exports = { spotifyGenres };
